//! # gRPC Service Implementation
//!
//! This module implements the WardenService gRPC endpoints defined in proto/warden.proto.
//! It provides bidirectional streaming for telemetry and decision events.
//!
//! The proto code is generated by build.rs using tonic-build.

use std::collections::HashMap;
use std::sync::Arc;
use tokio::sync::RwLock;
use tonic::{async_trait, Request, Response, Status, Streaming};
use uuid::Uuid;

use crate::warden::{Warden, WardenAction, Warden'sActionType, RiskLevel as WardenRiskLevel};

// Include the generated proto code
mod grpc_proto {
    include!("warden.pb.rs");
}

pub use grpc_proto::*;

/// WardenService state shared across all RPC methods
pub struct WardenServiceState {
    /// The Warden instance for scoring actions
    pub warden: Arc<Warden>,
    /// Decision event stream subscribers
    pub decision_subscribers: Arc<RwLock<Vec<tokio::sync::mpsc::Sender<DecisionEvent>>>>,
    /// Current containment status
    pub containment_status: Arc<RwLock<ContainmentStatus>>,
    /// Current cognitive mode
    pub cognitive_mode: Arc<RwLock<CognitiveMode>>,
    /// System metrics
    pub metrics: Arc<SystemMetrics>,
}

/// System metrics for telemetry
#[derive(Debug, Clone)]
pub struct SystemMetrics {
    pub metabolic_energy: f32,
    pub cpu_usage: f32,
    pub memory_usage: f32,
    pub tick_rate: f32,
    pub ipc_latency_ms: f32,
    pub active_agent_count: u32,
    pub decision_throughput: f32,
    pub pending_proposal_queue: u32,
}

impl Default for SystemMetrics {
    fn default() -> Self {
        SystemMetrics {
            metabolic_energy: 100.0,
            cpu_usage: 0.0,
            memory_usage: 0.0,
            tick_rate: 0.0,
            ipc_latency_ms: 0.0,
            active_agent_count: 0,
            decision_throughput: 0.0,
            pending_proposal_queue: 0,
        }
    }
}

impl WardenServiceState {
    /// Create a new WardenServiceState
    pub fn new() -> Self {
        WardenServiceState {
            warden: Arc::new(Warden::new()),
            decision_subscribers: Arc::new(RwLock::new(Vec::new())),
            containment_status: Arc::new(RwLock::new(ContainmentStatus::Inactive)),
            cognitive_mode: Arc::new(RwLock::new(CognitiveMode::Active)),
            metrics: Arc::new(SystemMetrics::default()),
        }
    }

    /// Update system metrics (called periodically)
    pub fn update_metrics(&self, metrics: SystemMetrics) {
        *self.metrics.clone() = metrics;
    }

    /// Broadcast a decision event to all subscribers
    pub async fn broadcast_decision(&self, event: DecisionEvent) {
        let subscribers = self.decision_subscribers.read().await;
        for sender in subscribers.iter() {
            let _ = sender.send(event.clone()).await;
        }
    }
}

impl Default for WardenServiceState {
    fn default() -> Self {
        Self::new()
    }
}

/// The WardenService implementation
pub struct WardenServiceImpl {
    state: Arc<WardenServiceState>,
}

impl WardenServiceImpl {
    /// Create a new WardenServiceImpl
    pub fn new(state: Arc<WardenServiceState>) -> Self {
        WardenServiceImpl { state }
    }
}

#[async_trait]
impl warden_service::WardenService for WardenServiceImpl {
    /// StreamTelemetry - Full-duplex telemetry stream
    async fn stream_telemetry(
        &self,
        request: Request<Streaming<TelemetryRequest>>,
    ) -> Result<Response<Streaming<TelemetryResponse>>, Status> {
        log::info!("📡 StreamTelemetry: Client connected");

        let mut stream = request.into_inner();
        
        // Get the first request to configure the stream
        let config = match stream.message().await {
            Ok(Some(req)) => req,
            Ok(None) => TelemetryRequest::default(),
            Err(e) => {
                log::error!("📡 StreamTelemetry: Failed to get config: {}", e);
                return Err(Status::internal(format!("Failed to get config: {}", e)));
            }
        };

        let interval_ms = config.interval_ms.max(100).min(10000);
        let state = self.state.clone();

        // Create a channel for the response stream
        let (tx, rx) = tokio::sync::mpsc::channel(100);

        // Spawn the telemetry streaming task
        tokio::spawn(async move {
            let mut interval = tokio::time::interval(tokio::time::Duration::from_millis(interval_ms as u64));
            
            loop {
                tokio::select! {
                    _ = interval.tick() => {
                        // Check if client disconnected
                        if tx.is_closed() {
                            log::info!("📡 StreamTelemetry: Client disconnected");
                            break;
                        }

                        // Get current metrics
                        let metrics = state.metrics.as_ref().clone();
                        let cognitive_mode = *state.cognitive_mode.read().await;

                        let response = TelemetryResponse {
                            timestamp: chrono::Utc::now().timestamp_millis(),
                            metabolic_energy: metrics.metabolic_energy,
                            cpu_usage: metrics.cpu_usage,
                            memory_usage: metrics.memory_usage,
                            tick_rate: metrics.tick_rate,
                            cognitive_mode,
                            agent_confidences: HashMap::new(),
                            ipc_latency_ms: metrics.ipc_latency_ms,
                            active_agent_count: metrics.active_agent_count,
                            decision_throughput: metrics.decision_throughput,
                            pending_proposal_queue: metrics.pending_proposal_queue,
                        };

                        if tx.send(Ok(response)).await.is_err() {
                            log::info!("📡 StreamTelemetry: Failed to send, client may have disconnected");
                            break;
                        }
                    }
                    _ = tokio::time::sleep(tokio::time::Duration::from_millis(50)) => {
                        // Check for any control messages
                    }
                }
            }
        });

        Ok(Response::new(Box::new(
            tokio_stream::wrappers::ReceiverStream::new(rx)
        )))
    }

    /// SubmitProposal - Submit brain proposal for kernel approval
    async fn submit_proposal(
        &self,
        request: Request<ProposalRequest>,
    ) -> Result<Response<ProposalResponse>, Status> {
        let req = request.into_inner();
        log::info!("📝 SubmitProposal: {} from agent {}", req.proposal_id, req.agent_id);

        // Convert proto risk level to Warden risk level
        let warden_risk: WardenRiskLevel = match req.risk_level() {
            RiskLevel::ReadOnly => WardenRiskLevel::Negligible,
            RiskLevel::Low => WardenRiskLevel::Low,
            RiskLevel::Medium => WardenRiskLevel::Medium,
            RiskLevel::High => WardenRiskLevel::High,
            RiskLevel::Critical => WardenRiskLevel::Critical,
            _ => WardenRiskLevel::Medium,
        };

        // Create Warden action
        let action = WardenAction {
            id: req.proposal_id.clone(),
            action_type: Warden'sActionType::Execute,
            target: req.decision.clone(),
            payload: Some(req.reasoning.clone()),
            requested_by: req.agent_id.clone(),
            risk_level: warden_risk,
            timestamp: chrono::Utc::now(),
            context: req.metadata.clone(),
        };

        // Evaluate through Warden
        let decision = self.state.warden.evaluate(action).await;

        let status = if decision.score.approved {
            ProposalStatus::Approved
        } else {
            ProposalStatus::Vetoed
        };

        let response = ProposalResponse {
            proposal_id: req.proposal_id,
            status: ProposalStatus::into(status),
            message: if decision.score.approved {
                "Proposal approved by Warden".to_string()
            } else {
                format!("Proposal vetoed: {}", decision.score.reasons.join("; "))
            },
            processed_at: chrono::Utc::now().timestamp_millis(),
            kernel_id: decision.warden_id,
            metadata: HashMap::new(),
        };

        // Broadcast decision event
        let event = DecisionEvent {
            event_id: Uuid::new_v4().to_string(),
            timestamp: chrono::Utc::now().timestamp_millis(),
            event_type: DecisionEventType::DecisionMade,
            proposal_id: req.proposal_id,
            agent_id: req.agent_id,
            decision: decision.decision,
            status: if decision.score.approved {
                DecisionStatus::Approved
            } else {
                DecisionStatus::Rejected
            },
            confidence: decision.score.total as f32 / 100.0,
            risk_level: req.risk_level(),
            metadata: HashMap::new(),
        };
        self.state.broadcast_decision(event).await;

        log::info!("📝 SubmitProposal: Completed with status {:?}", response.status);
        Ok(Response::new(response))
    }

    /// RequestConfirmation - Request sovereign confirmation
    async fn request_confirmation(
        &self,
        request: Request<ConfirmationRequest>,
    ) -> Result<Response<ConfirmationResponse>, Status> {
        let req = request.into_inner();
        log::info!("🔐 RequestConfirmation: {} for action {}", req.confirmation_id, req.action);

        // For now, auto-approve based on risk level
        // In production, this would integrate with the SovereigntyGate
        let confirmed = match req.risk_level() {
            RiskLevel::ReadOnly | RiskLevel::Low => true,
            RiskLevel::Medium => true,
            RiskLevel::High | RiskLevel::Critical => false,
            _ => false,
        };

        let response = ConfirmationResponse {
            confirmation_id: req.confirmation_id,
            confirmed,
            message: if confirmed {
                "Confirmation granted".to_string()
            } else {
                "Action requires manual confirmation".to_string()
            },
            confirmed_at: chrono::Utc::now().timestamp_millis(),
            confirmer_id: "warden".to_string(),
            conditions: if confirmed { vec![] } else { vec!["Requires human approval".to_string()] },
        };

        // Broadcast confirmation request event
        let event = DecisionEvent {
            event_id: Uuid::new_v4().to_string(),
            timestamp: chrono::Utc::now().timestamp_millis(),
            event_type: DecisionEventType::ConfirmationRequested,
            proposal_id: req.confirmation_id,
            agent_id: req.requesting_agent_id,
            decision: req.action,
            status: if confirmed {
                DecisionStatus::Approved
            } else {
                DecisionStatus::PendingConfirmation
            },
            confidence: 1.0,
            risk_level: req.risk_level(),
            metadata: req.context.clone(),
        };
        self.state.broadcast_decision(event).await;

        log::info!("🔐 RequestConfirmation: {} - {}", req.confirmation_id, response.message);
        Ok(Response::new(response))
    }

    /// StreamDecisions - Subscribe to decision events
    async fn stream_decisions(
        &self,
        request: Request<DecisionRequest>,
    ) -> Result<Response<Streaming<DecisionEvent>>, Status> {
        log::info!("📊 StreamDecisions: Client subscribed");

        let _req = request.into_inner();

        // Create a channel for this subscriber
        let (tx, rx) = tokio::sync::mpsc::channel(100);

        // Register this subscriber
        {
            let mut subscribers = self.state.decision_subscribers.write().await;
            subscribers.push(tx.clone());
        }

        // Return the stream
        Ok(Response::new(Box::new(
            tokio_stream::wrappers::ReceiverStream::new(rx)
        )))
    }

    /// TriggerContainment - Emergency lockdown
    async fn trigger_containment(
        &self,
        request: Request<ContainmentRequest>,
    ) -> Result<Response<ContainmentResponse>, Status> {
        let req = request.into_inner();
        log::warn!("🚨 TriggerContainment: {} by {} (hard: {})", 
            req.reason, req.triggered_by, req.hard_containment);

        let status = if req.hard_containment {
            ContainmentStatus::Escalated
        } else {
            ContainmentStatus::Active
        };

        // Update containment status
        *self.state.containment_status.write().await = status;

        // Broadcast containment event
        let event = DecisionEvent {
            event_id: Uuid::new_v4().to_string(),
            timestamp: chrono::Utc::now().timestamp_millis(),
            event_type: DecisionEventType::ContainmentTriggered,
            proposal_id: String::new(),
            agent_id: req.triggered_by.clone(),
            decision: req.reason.clone(),
            status: DecisionStatus::Contained,
            confidence: 1.0,
            risk_level: RiskLevel::Critical,
            metadata: HashMap::new(),
        };
        self.state.broadcast_decision(event).await;

        let response = ContainmentResponse {
            success: true,
            status: ContainmentStatus::into(status),
            message: format!("Containment activated: {}", req.reason),
            activated_at: chrono::Utc::now().timestamp_millis(),
            instructions: vec![
                "All agent operations halted".to_string(),
                "Kernel isolation active".to_string(),
                "Awaiting manual review".to_string(),
            ],
            tpm_registers: HashMap::new(),
            containment_id: Uuid::new_v4().to_string(),
        };

        log::warn!("🚨 TriggerContainment: Activated - {}", response.containment_id);
        Ok(Response::new(response))
    }
}

// =============================================================================
// gRPC Server Builder
// =============================================================================

/// Build and start the gRPC server
pub async fn start_grpc_server(
    state: Arc<WardenServiceState>,
    port: u16,
) -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
    let addr = format!("[::0]:{}", port).parse()?;
    
    log::info!("🔌 Starting gRPC server on port {}", port);

    use warden_service::WardenServiceServer;

    let service = WardenServiceImpl::new(state);

    tonic::transport::Server::builder()
        .add_service(WardenServiceServer::new(service))
        .serve(addr)
        .await?;

    Ok(())
}
