// This file is @generated by prost-build.
/// / Request for telemetry data streaming
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TelemetryRequest {
    /// / Interval in milliseconds between telemetry updates
    #[prost(uint32, tag = "1")]
    pub interval_ms: u32,
    /// / Include agent-specific metrics
    #[prost(bool, tag = "2")]
    pub include_agents: bool,
    /// / Include IPC latency metrics
    #[prost(bool, tag = "3")]
    pub include_ipc_latency: bool,
    /// / Request specific metric categories
    #[prost(string, repeated, tag = "4")]
    pub metric_categories: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// / Response containing system telemetry data
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TelemetryResponse {
    /// / Timestamp of the telemetry reading (Unix epoch milliseconds)
    #[prost(int64, tag = "1")]
    pub timestamp: i64,
    /// / Metabolic energy level (0-100)
    #[prost(float, tag = "2")]
    pub metabolic_energy: f32,
    /// / CPU usage percentage (0-100)
    #[prost(float, tag = "3")]
    pub cpu_usage: f32,
    /// / Memory usage percentage (0-100)
    #[prost(float, tag = "4")]
    pub memory_usage: f32,
    /// / Current tick rate (ticks per second)
    #[prost(float, tag = "5")]
    pub tick_rate: f32,
    /// / Current cognitive mode
    #[prost(enumeration = "CognitiveMode", tag = "6")]
    pub cognitive_mode: i32,
    /// / Agent confidence scores (agent_id -> confidence)
    #[prost(map = "string, float", tag = "7")]
    pub agent_confidences: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        f32,
    >,
    /// / IPC latency in milliseconds
    #[prost(float, tag = "8")]
    pub ipc_latency_ms: f32,
    /// / Active agent count
    #[prost(uint32, tag = "9")]
    pub active_agent_count: u32,
    /// / Decision throughput (decisions per second)
    #[prost(float, tag = "10")]
    pub decision_throughput: f32,
    /// / Queue depth for pending proposals
    #[prost(uint32, tag = "11")]
    pub pending_proposal_queue: u32,
}
/// / Request to submit a brain proposal for kernel approval
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProposalRequest {
    /// / Unique identifier for the proposal
    #[prost(string, tag = "1")]
    pub proposal_id: ::prost::alloc::string::String,
    /// / ID of the agent submitting the proposal
    #[prost(string, tag = "2")]
    pub agent_id: ::prost::alloc::string::String,
    /// / Type of agent submitting the proposal
    #[prost(enumeration = "AgentType", tag = "3")]
    pub agent_type: i32,
    /// / The proposed decision or action
    #[prost(string, tag = "4")]
    pub decision: ::prost::alloc::string::String,
    /// / Confidence score (0.0-1.0)
    #[prost(float, tag = "5")]
    pub confidence: f32,
    /// / Reasoning behind the proposal
    #[prost(string, tag = "6")]
    pub reasoning: ::prost::alloc::string::String,
    /// / Evidence supporting the proposal
    #[prost(string, repeated, tag = "7")]
    pub evidence: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// / Additional metadata
    #[prost(map = "string, string", tag = "8")]
    pub metadata: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    /// / Expected risk level of the proposal
    #[prost(enumeration = "RiskLevel", tag = "9")]
    pub risk_level: i32,
}
/// / Response to a proposal submission
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProposalResponse {
    /// / The proposal ID (echoed back)
    #[prost(string, tag = "1")]
    pub proposal_id: ::prost::alloc::string::String,
    /// / Status of the proposal
    #[prost(enumeration = "ProposalStatus", tag = "2")]
    pub status: i32,
    /// / Human-readable status message
    #[prost(string, tag = "3")]
    pub message: ::prost::alloc::string::String,
    /// / Timestamp when the proposal was processed
    #[prost(int64, tag = "4")]
    pub processed_at: i64,
    /// / Optional: ID of the kernel that approved/vetoed
    #[prost(string, tag = "5")]
    pub kernel_id: ::prost::alloc::string::String,
    /// / Optional: Additional response metadata
    #[prost(map = "string, string", tag = "6")]
    pub metadata: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
/// / Request for sovereign confirmation of an action
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConfirmationRequest {
    /// / Unique identifier for the confirmation request
    #[prost(string, tag = "1")]
    pub confirmation_id: ::prost::alloc::string::String,
    /// / The action requiring confirmation
    #[prost(string, tag = "2")]
    pub action: ::prost::alloc::string::String,
    /// / Risk level of the action
    #[prost(enumeration = "RiskLevel", tag = "3")]
    pub risk_level: i32,
    /// / Required capability for this action
    #[prost(string, tag = "4")]
    pub required_capability: ::prost::alloc::string::String,
    /// / Agent requesting confirmation
    #[prost(string, tag = "5")]
    pub requesting_agent_id: ::prost::alloc::string::String,
    /// / Additional context for the confirmation
    #[prost(map = "string, string", tag = "6")]
    pub context: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    /// / Timeout in seconds
    #[prost(uint32, tag = "7")]
    pub timeout_seconds: u32,
}
/// / Response to a confirmation request
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConfirmationResponse {
    /// / Confirmation ID (echoed back)
    #[prost(string, tag = "1")]
    pub confirmation_id: ::prost::alloc::string::String,
    /// / Whether confirmation was granted
    #[prost(bool, tag = "2")]
    pub confirmed: bool,
    /// / Human-readable response message
    #[prost(string, tag = "3")]
    pub message: ::prost::alloc::string::String,
    /// / Timestamp of the confirmation
    #[prost(int64, tag = "4")]
    pub confirmed_at: i64,
    /// / Optional: Confirmer identity
    #[prost(string, tag = "5")]
    pub confirmer_id: ::prost::alloc::string::String,
    /// / Optional: Conditions or limitations
    #[prost(string, repeated, tag = "6")]
    pub conditions: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// / Request to subscribe to decision events
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DecisionRequest {
    /// / Filter by specific agent IDs
    #[prost(string, repeated, tag = "1")]
    pub filter_agent_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// / Filter by event types
    #[prost(enumeration = "DecisionEventType", repeated, tag = "2")]
    pub filter_event_types: ::prost::alloc::vec::Vec<i32>,
    /// / Filter by decision status
    #[prost(enumeration = "DecisionStatus", repeated, tag = "3")]
    pub filter_statuses: ::prost::alloc::vec::Vec<i32>,
    /// / Include historical events (from the last N seconds)
    #[prost(uint32, tag = "4")]
    pub history_seconds: u32,
    /// / Maximum events per second to stream
    #[prost(uint32, tag = "5")]
    pub max_events_per_second: u32,
}
/// / Event representing a decision or state change
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DecisionEvent {
    /// / Unique event identifier
    #[prost(string, tag = "1")]
    pub event_id: ::prost::alloc::string::String,
    /// / Timestamp of the event (Unix epoch milliseconds)
    #[prost(int64, tag = "2")]
    pub timestamp: i64,
    /// / Type of decision event
    #[prost(enumeration = "DecisionEventType", tag = "3")]
    pub event_type: i32,
    /// / Associated proposal ID (if applicable)
    #[prost(string, tag = "4")]
    pub proposal_id: ::prost::alloc::string::String,
    /// / Agent that generated the event
    #[prost(string, tag = "5")]
    pub agent_id: ::prost::alloc::string::String,
    /// / The decision made
    #[prost(string, tag = "6")]
    pub decision: ::prost::alloc::string::String,
    /// / Status of the decision
    #[prost(enumeration = "DecisionStatus", tag = "7")]
    pub status: i32,
    /// / Confidence score (0.0-1.0)
    #[prost(float, tag = "8")]
    pub confidence: f32,
    /// / Risk level
    #[prost(enumeration = "RiskLevel", tag = "9")]
    pub risk_level: i32,
    /// / Additional event metadata
    #[prost(map = "string, string", tag = "10")]
    pub metadata: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
/// / Request to trigger emergency containment
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ContainmentRequest {
    /// / Reason for triggering containment
    #[prost(string, tag = "1")]
    pub reason: ::prost::alloc::string::String,
    /// / ID of the agent or system triggering containment
    #[prost(string, tag = "2")]
    pub triggered_by: ::prost::alloc::string::String,
    /// / Whether this is a hard containment (cannot be overridden)
    #[prost(bool, tag = "3")]
    pub hard_containment: bool,
    /// / Optional: Specific agents to contain (empty = all)
    #[prost(string, repeated, tag = "4")]
    pub target_agent_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// / Optional: Scope of containment
    #[prost(string, tag = "5")]
    pub scope: ::prost::alloc::string::String,
    /// / TPM registers to verify (base64 encoded)
    #[prost(string, repeated, tag = "6")]
    pub tpm_registers: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// / Response to a containment trigger
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ContainmentResponse {
    /// / Whether containment was successfully activated
    #[prost(bool, tag = "1")]
    pub success: bool,
    /// / Current containment status
    #[prost(enumeration = "ContainmentStatus", tag = "2")]
    pub status: i32,
    /// / Human-readable status message
    #[prost(string, tag = "3")]
    pub message: ::prost::alloc::string::String,
    /// / Timestamp when containment was activated
    #[prost(int64, tag = "4")]
    pub activated_at: i64,
    /// / Instructions for human operator (if any)
    #[prost(string, repeated, tag = "5")]
    pub instructions: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// / TPM registers state (for verification)
    #[prost(map = "string, string", tag = "6")]
    pub tpm_registers: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    /// / Containment ID
    #[prost(string, tag = "7")]
    pub containment_id: ::prost::alloc::string::String,
}
/// / Status of a brain proposal submitted for kernel approval
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ProposalStatus {
    Unspecified = 0,
    Pending = 1,
    Approved = 2,
    Vetoed = 3,
}
impl ProposalStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "PROPOSAL_STATUS_UNSPECIFIED",
            Self::Pending => "PROPOSAL_STATUS_PENDING",
            Self::Approved => "PROPOSAL_STATUS_APPROVED",
            Self::Vetoed => "PROPOSAL_STATUS_VETOED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PROPOSAL_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "PROPOSAL_STATUS_PENDING" => Some(Self::Pending),
            "PROPOSAL_STATUS_APPROVED" => Some(Self::Approved),
            "PROPOSAL_STATUS_VETOED" => Some(Self::Vetoed),
            _ => None,
        }
    }
}
/// / Risk level classification for actions and confirmations
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum RiskLevel {
    Unspecified = 0,
    ReadOnly = 1,
    Low = 2,
    Medium = 3,
    High = 4,
    Critical = 5,
}
impl RiskLevel {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "RISK_LEVEL_UNSPECIFIED",
            Self::ReadOnly => "RISK_LEVEL_READ_ONLY",
            Self::Low => "RISK_LEVEL_LOW",
            Self::Medium => "RISK_LEVEL_MEDIUM",
            Self::High => "RISK_LEVEL_HIGH",
            Self::Critical => "RISK_LEVEL_CRITICAL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "RISK_LEVEL_UNSPECIFIED" => Some(Self::Unspecified),
            "RISK_LEVEL_READ_ONLY" => Some(Self::ReadOnly),
            "RISK_LEVEL_LOW" => Some(Self::Low),
            "RISK_LEVEL_MEDIUM" => Some(Self::Medium),
            "RISK_LEVEL_HIGH" => Some(Self::High),
            "RISK_LEVEL_CRITICAL" => Some(Self::Critical),
            _ => None,
        }
    }
}
/// / Cognitive mode of the adaptive kernel
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CognitiveMode {
    Unspecified = 0,
    Active = 1,
    Idle = 2,
    Sleep = 3,
    Dream = 4,
    Emergency = 5,
}
impl CognitiveMode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "COGNITIVE_MODE_UNSPECIFIED",
            Self::Active => "COGNITIVE_MODE_ACTIVE",
            Self::Idle => "COGNITIVE_MODE_IDLE",
            Self::Sleep => "COGNITIVE_MODE_SLEEP",
            Self::Dream => "COGNITIVE_MODE_DREAM",
            Self::Emergency => "COGNITIVE_MODE_EMERGENCY",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "COGNITIVE_MODE_UNSPECIFIED" => Some(Self::Unspecified),
            "COGNITIVE_MODE_ACTIVE" => Some(Self::Active),
            "COGNITIVE_MODE_IDLE" => Some(Self::Idle),
            "COGNITIVE_MODE_SLEEP" => Some(Self::Sleep),
            "COGNITIVE_MODE_DREAM" => Some(Self::Dream),
            "COGNITIVE_MODE_EMERGENCY" => Some(Self::Emergency),
            _ => None,
        }
    }
}
/// / Event type for decision streaming
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum DecisionEventType {
    Unspecified = 0,
    ProposalReceived = 1,
    DecisionMade = 2,
    ConfirmationRequested = 3,
    ContainmentTriggered = 4,
    KernelStateChange = 5,
}
impl DecisionEventType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "DECISION_EVENT_TYPE_UNSPECIFIED",
            Self::ProposalReceived => "DECISION_EVENT_TYPE_PROPOSAL_RECEIVED",
            Self::DecisionMade => "DECISION_EVENT_TYPE_DECISION_MADE",
            Self::ConfirmationRequested => "DECISION_EVENT_TYPE_CONFIRMATION_REQUESTED",
            Self::ContainmentTriggered => "DECISION_EVENT_TYPE_CONTAINMENT_TRIGGERED",
            Self::KernelStateChange => "DECISION_EVENT_TYPE_KERNEL_STATE_CHANGE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "DECISION_EVENT_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "DECISION_EVENT_TYPE_PROPOSAL_RECEIVED" => Some(Self::ProposalReceived),
            "DECISION_EVENT_TYPE_DECISION_MADE" => Some(Self::DecisionMade),
            "DECISION_EVENT_TYPE_CONFIRMATION_REQUESTED" => {
                Some(Self::ConfirmationRequested)
            }
            "DECISION_EVENT_TYPE_CONTAINMENT_TRIGGERED" => {
                Some(Self::ContainmentTriggered)
            }
            "DECISION_EVENT_TYPE_KERNEL_STATE_CHANGE" => Some(Self::KernelStateChange),
            _ => None,
        }
    }
}
/// / Status of a decision event
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum DecisionStatus {
    Unspecified = 0,
    Processing = 1,
    Approved = 2,
    Rejected = 3,
    PendingConfirmation = 4,
    Contained = 5,
}
impl DecisionStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "DECISION_STATUS_UNSPECIFIED",
            Self::Processing => "DECISION_STATUS_PROCESSING",
            Self::Approved => "DECISION_STATUS_APPROVED",
            Self::Rejected => "DECISION_STATUS_REJECTED",
            Self::PendingConfirmation => "DECISION_STATUS_PENDING_CONFIRMATION",
            Self::Contained => "DECISION_STATUS_CONTAINED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "DECISION_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "DECISION_STATUS_PROCESSING" => Some(Self::Processing),
            "DECISION_STATUS_APPROVED" => Some(Self::Approved),
            "DECISION_STATUS_REJECTED" => Some(Self::Rejected),
            "DECISION_STATUS_PENDING_CONFIRMATION" => Some(Self::PendingConfirmation),
            "DECISION_STATUS_CONTAINED" => Some(Self::Contained),
            _ => None,
        }
    }
}
/// / Agent type for proposal attribution
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum AgentType {
    Unspecified = 0,
    Code = 1,
    Strategist = 2,
    Auditor = 3,
    Executor = 4,
    Evolution = 5,
    Mindmap = 6,
    PolicyValidator = 7,
    WebSearch = 8,
}
impl AgentType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "AGENT_TYPE_UNSPECIFIED",
            Self::Code => "AGENT_TYPE_CODE",
            Self::Strategist => "AGENT_TYPE_STRATEGIST",
            Self::Auditor => "AGENT_TYPE_AUDITOR",
            Self::Executor => "AGENT_TYPE_EXECUTOR",
            Self::Evolution => "AGENT_TYPE_EVOLUTION",
            Self::Mindmap => "AGENT_TYPE_MINDMAP",
            Self::PolicyValidator => "AGENT_TYPE_POLICY_VALIDATOR",
            Self::WebSearch => "AGENT_TYPE_WEB_SEARCH",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "AGENT_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "AGENT_TYPE_CODE" => Some(Self::Code),
            "AGENT_TYPE_STRATEGIST" => Some(Self::Strategist),
            "AGENT_TYPE_AUDITOR" => Some(Self::Auditor),
            "AGENT_TYPE_EXECUTOR" => Some(Self::Executor),
            "AGENT_TYPE_EVOLUTION" => Some(Self::Evolution),
            "AGENT_TYPE_MINDMAP" => Some(Self::Mindmap),
            "AGENT_TYPE_POLICY_VALIDATOR" => Some(Self::PolicyValidator),
            "AGENT_TYPE_WEB_SEARCH" => Some(Self::WebSearch),
            _ => None,
        }
    }
}
/// / Containment status
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ContainmentStatus {
    Unspecified = 0,
    Inactive = 1,
    Active = 2,
    Escalated = 3,
    Resolved = 4,
}
impl ContainmentStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "CONTAINMENT_STATUS_UNSPECIFIED",
            Self::Inactive => "CONTAINMENT_STATUS_INACTIVE",
            Self::Active => "CONTAINMENT_STATUS_ACTIVE",
            Self::Escalated => "CONTAINMENT_STATUS_ESCALATED",
            Self::Resolved => "CONTAINMENT_STATUS_RESOLVED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CONTAINMENT_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "CONTAINMENT_STATUS_INACTIVE" => Some(Self::Inactive),
            "CONTAINMENT_STATUS_ACTIVE" => Some(Self::Active),
            "CONTAINMENT_STATUS_ESCALATED" => Some(Self::Escalated),
            "CONTAINMENT_STATUS_RESOLVED" => Some(Self::Resolved),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod warden_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// / Warden service for OS-level operations and brain integration
    #[derive(Debug, Clone)]
    pub struct WardenServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl WardenServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> WardenServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> WardenServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            WardenServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// / StreamTelemetry - Full-duplex telemetry stream
        /// / Client sends TelemetryRequest with streaming parameters
        /// / Server streams TelemetryResponse with system metrics
        pub async fn stream_telemetry(
            &mut self,
            request: impl tonic::IntoStreamingRequest<Message = super::TelemetryRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::TelemetryResponse>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/warden.WardenService/StreamTelemetry",
            );
            let mut req = request.into_streaming_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("warden.WardenService", "StreamTelemetry"));
            self.inner.streaming(req, path, codec).await
        }
        /// / SubmitProposal - Submit brain proposal for kernel approval
        /// / Blocks until proposal is processed by the kernel
        pub async fn submit_proposal(
            &mut self,
            request: impl tonic::IntoRequest<super::ProposalRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ProposalResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/warden.WardenService/SubmitProposal",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("warden.WardenService", "SubmitProposal"));
            self.inner.unary(req, path, codec).await
        }
        /// / RequestConfirmation - Request sovereign confirmation
        /// / Used for high-risk operations requiring human-in-the-loop
        pub async fn request_confirmation(
            &mut self,
            request: impl tonic::IntoRequest<super::ConfirmationRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ConfirmationResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/warden.WardenService/RequestConfirmation",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("warden.WardenService", "RequestConfirmation"));
            self.inner.unary(req, path, codec).await
        }
        /// / StreamDecisions - Subscribe to decision events
        /// / Server streams DecisionEvent messages to the client
        pub async fn stream_decisions(
            &mut self,
            request: impl tonic::IntoRequest<super::DecisionRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::DecisionEvent>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/warden.WardenService/StreamDecisions",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("warden.WardenService", "StreamDecisions"));
            self.inner.server_streaming(req, path, codec).await
        }
        /// / TriggerContainment - Emergency lockdown
        /// / Immediately halts agent operations and isolates the kernel
        pub async fn trigger_containment(
            &mut self,
            request: impl tonic::IntoRequest<super::ContainmentRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ContainmentResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/warden.WardenService/TriggerContainment",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("warden.WardenService", "TriggerContainment"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod warden_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with WardenServiceServer.
    #[async_trait]
    pub trait WardenService: std::marker::Send + std::marker::Sync + 'static {
        /// Server streaming response type for the StreamTelemetry method.
        type StreamTelemetryStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::TelemetryResponse, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        /// / StreamTelemetry - Full-duplex telemetry stream
        /// / Client sends TelemetryRequest with streaming parameters
        /// / Server streams TelemetryResponse with system metrics
        async fn stream_telemetry(
            &self,
            request: tonic::Request<tonic::Streaming<super::TelemetryRequest>>,
        ) -> std::result::Result<
            tonic::Response<Self::StreamTelemetryStream>,
            tonic::Status,
        >;
        /// / SubmitProposal - Submit brain proposal for kernel approval
        /// / Blocks until proposal is processed by the kernel
        async fn submit_proposal(
            &self,
            request: tonic::Request<super::ProposalRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ProposalResponse>,
            tonic::Status,
        >;
        /// / RequestConfirmation - Request sovereign confirmation
        /// / Used for high-risk operations requiring human-in-the-loop
        async fn request_confirmation(
            &self,
            request: tonic::Request<super::ConfirmationRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ConfirmationResponse>,
            tonic::Status,
        >;
        /// Server streaming response type for the StreamDecisions method.
        type StreamDecisionsStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::DecisionEvent, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        /// / StreamDecisions - Subscribe to decision events
        /// / Server streams DecisionEvent messages to the client
        async fn stream_decisions(
            &self,
            request: tonic::Request<super::DecisionRequest>,
        ) -> std::result::Result<
            tonic::Response<Self::StreamDecisionsStream>,
            tonic::Status,
        >;
        /// / TriggerContainment - Emergency lockdown
        /// / Immediately halts agent operations and isolates the kernel
        async fn trigger_containment(
            &self,
            request: tonic::Request<super::ContainmentRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ContainmentResponse>,
            tonic::Status,
        >;
    }
    /// / Warden service for OS-level operations and brain integration
    #[derive(Debug)]
    pub struct WardenServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> WardenServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for WardenServiceServer<T>
    where
        T: WardenService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/warden.WardenService/StreamTelemetry" => {
                    #[allow(non_camel_case_types)]
                    struct StreamTelemetrySvc<T: WardenService>(pub Arc<T>);
                    impl<
                        T: WardenService,
                    > tonic::server::StreamingService<super::TelemetryRequest>
                    for StreamTelemetrySvc<T> {
                        type Response = super::TelemetryResponse;
                        type ResponseStream = T::StreamTelemetryStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                tonic::Streaming<super::TelemetryRequest>,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as WardenService>::stream_telemetry(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = StreamTelemetrySvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/warden.WardenService/SubmitProposal" => {
                    #[allow(non_camel_case_types)]
                    struct SubmitProposalSvc<T: WardenService>(pub Arc<T>);
                    impl<
                        T: WardenService,
                    > tonic::server::UnaryService<super::ProposalRequest>
                    for SubmitProposalSvc<T> {
                        type Response = super::ProposalResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ProposalRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as WardenService>::submit_proposal(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SubmitProposalSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/warden.WardenService/RequestConfirmation" => {
                    #[allow(non_camel_case_types)]
                    struct RequestConfirmationSvc<T: WardenService>(pub Arc<T>);
                    impl<
                        T: WardenService,
                    > tonic::server::UnaryService<super::ConfirmationRequest>
                    for RequestConfirmationSvc<T> {
                        type Response = super::ConfirmationResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ConfirmationRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as WardenService>::request_confirmation(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = RequestConfirmationSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/warden.WardenService/StreamDecisions" => {
                    #[allow(non_camel_case_types)]
                    struct StreamDecisionsSvc<T: WardenService>(pub Arc<T>);
                    impl<
                        T: WardenService,
                    > tonic::server::ServerStreamingService<super::DecisionRequest>
                    for StreamDecisionsSvc<T> {
                        type Response = super::DecisionEvent;
                        type ResponseStream = T::StreamDecisionsStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::DecisionRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as WardenService>::stream_decisions(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = StreamDecisionsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/warden.WardenService/TriggerContainment" => {
                    #[allow(non_camel_case_types)]
                    struct TriggerContainmentSvc<T: WardenService>(pub Arc<T>);
                    impl<
                        T: WardenService,
                    > tonic::server::UnaryService<super::ContainmentRequest>
                    for TriggerContainmentSvc<T> {
                        type Response = super::ContainmentResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ContainmentRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as WardenService>::trigger_containment(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = TriggerContainmentSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(empty_body());
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for WardenServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "warden.WardenService";
    impl<T> tonic::server::NamedService for WardenServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
