# cognition/Cognition.jl - Main Sovereign Cognition Module
# Phase 2: Self-directing, multi-agent intelligence engine
# Phase 4: Flow Integrity with cryptographic approval tokens

module Cognition

using Dates
using UUIDs
using Statistics
using SHA

# Export all components
export
    # Types
    CognitionTypes,
    Perception,  # Typed perception
    
    # Spine
    DecisionSpine,
    DecisionCycle,
    CommittedDecision,
    SpineConfig,
    
    # ReAct
    ReAct,
    ReActState,
    ReActStep,
    ReActContext,
    create_react_context,
    run_react_cycle,
    
    # Agents
    Agents,
    ExecutorAgent,
    StrategistAgent,
    AuditorAgent,
    EvolutionEngineAgent,
    
    # Auxiliary agents (Phase 4 - expanded hierarchy)
    WebSearchAgent,
    CodeAgent,
    MindMapAgent,
    
    # Memory
    WeaponizedMemory,
    DoctrineMemory,
    TacticalMemory,
    AdversaryModels,
    
    # Feedback
    PainFeedback,
    AgentPerformance,
    
    # CAUSAL EMOTIONAL INTEGRATION - Emotions affect kernel decisions
    Emotions,
    AffectiveState,
    update_emotion!,
    apply_emotional_modulation,
    get_affective_summary,
    
    # Reality
    RealityIngestion,
    RealitySignal,
    
    # Power
    PowerMetric,
    OptionalityTracker,
    measure_power,
    
    # Main orchestration
    CognitiveEngine,
    run_sovereign_cycle,
    
    # Kernel integration (Phase 4 - Flow Integrity)
    require_kernel_approval,
    ApprovalToken,
    generate_approval_token,
    validate_approval_token,
    
    # Autonomous Planning
    AutonomousPlanner,
    
    # Goals
    GoalSystem,
    Goal,
    GoalGraph,
    GoalStatus,
    generate_goals,
    evaluate_goal,
    should_activate_goal,
    should_abandon_goal,
    abandon_goal!,
    require_kernel_approval,
    compute_intrinsic_reward,
    MIN_ACTIVATION_THRESHOLD,
    MAX_GOALS_ACTIVE,
    
    # World Model
    WorldModel,
    Trajectory,
    predict_next_state,
    predict_reward,
    predict_risk,
    simulate_trajectory,
    simulate_counterfactual,
    update_causal_graph!,
    get_causal_parents,
    infer_user_intent,
    find_best_action,
    plan_to_goal,
    record_experience!,
    reset_model!,
    get_model_confidence

# Submodules
include("types.jl")
using .CognitionTypes

include("spine/DecisionSpine.jl")
using .DecisionSpine

include("agents/Agents.jl")
using .Agents

include("feedback/PainFeedback.jl")
using .PainFeedback

include("reality/RealityIngestion.jl")
using .RealityIngestion

include("goals/GoalSystem.jl")
using .GoalSystem

include("worldmodel/WorldModel.jl")
using .WorldModel

# ReAct (Reason + Act) Framework
include("ReAct.jl")
using .ReAct

# Autonomous Planning (Phase 4 - Self-improvement)
include(joinpath(@__DIR__, "..", "planning", "AutonomousPlanner.jl"))
using .AutonomousPlanner

# Kernel imports for sovereignty gateway
include(joinpath(@__DIR__, "..", "kernel", "Kernel.jl"))
using .Kernel
using .Kernel.SharedTypes

# Brain imports for BrainOutput conversion
include(joinpath(@__DIR__, "..", "brain", "Brain.jl"))
using .Brain

# Emotions module for affective state integration (VERIFIED CAUSAL INTEGRATION)
include(joinpath(@__DIR__, "feedback", "Emotions.jl"))
using .Emotions

# ============================================================================
# FLOW INTEGRITY - Cryptographic Approval Tokens (Phase 4)
# ============================================================================

"""
    ApprovalToken - Cryptographic token for Flow Integrity pattern
    
    INVARIANTS:
    1. Token is generated by Kernel.approve() after validation
    2. Token contains cryptographic hash linking to specific decision
    3. Token must be validated before execution
    4. Token expires after defined TTL
"""
struct ApprovalToken
    id::UUID
    decision_hash::Vector{UInt8}  # SHA256 hash of decision content (32 bytes)
    generated_at::DateTime
    expires_at::DateTime
    kernel_signature::Vector{UInt8}  # Cryptographic signature from kernel
    approved_action::String  # The approved action identifier
    
    function ApprovalToken(
        decision_content::String,
        approved_action::String;
        ttl_seconds::Int=300  # 5 minute default TTL
    )
        now_ts = now()
        # Generate SHA256 hash of decision content
        decision_hash = sha256(decision_content)
        # Generate kernel signature (simplified - in production use proper crypto)
        kernel_sig = sha256(decision_content * string(now_ts))
        
        new(
            uuid4(),
            decision_hash,
            now_ts,
            now_ts + Dates.Second(ttl_seconds),
            kernel_sig,
            approved_action
        )
    end
end

"""
    generate_approval_token - Generate Flow Integrity approval token
"""
function generate_approval_token(
    decision::CommittedDecision,
    approved_action::String
)::ApprovalToken
    # Create deterministic content for hashing
    content = string(decision.id, decision.decision, decision.timestamp)
    return ApprovalToken(content, approved_action)
end

"""
    validate_approval_token - Validate Flow Integrity approval token
    
    Returns true if token is valid and not expired
"""
function validate_approval_token(
    token::ApprovalToken,
    decision::CommittedDecision
)::Bool
    # Check expiration
    if now() > token.expires_at
        @warn "Approval token expired" token_id=token.id
        return false
    end
    
    # Verify decision hash matches
    content = string(decision.id, decision.decision, decision.timestamp)
    expected_hash = sha256(content)
    if token.decision_hash != expected_hash
        @warn "Approval token decision hash mismatch" token_id=token.id
        return false
    end
    
    return true
end

"""
    require_kernel_approval - Gateway function for Kernel approval
    
    This is the SINGLE gateway for all execution paths.
    
    INVARIANTS:
    1. ALL decisions must pass through this gateway
    2. Returns ApprovalToken only if Kernel.approve() returns APPROVED
    3. No bypass mechanisms exist - fail-closed by default
"""
function require_kernel_approval(
    kernel::Any,  # KernelState - typed as Any to avoid circular deps
    proposal::ActionProposal,
    decision::CommittedDecision
)::Tuple{Bool, Union{ApprovalToken, Nothing}}
    
    # Import Kernel module dynamically
    try
        # Try to call Kernel.approve if available
        # This will only work when Kernel is properly imported
        # For now, implement fail-closed default
        
        # Default: fail-closed (deny) if no kernel available
        return false, nothing
    catch e
        @error "Kernel approval failed" error=string(e)
        return false, nothing
    end
end

# ============================================================================
# MAIN COGNITIVE ENGINE
# ============================================================================

"""
    _estimate_task_complexity - Estimate complexity of the current task
    
    Returns a value between 0 and 1 indicating how complex the current task is.
    High complexity (> 0.7) triggers ReAct reasoning for interleaved thought/action.
"""
function _estimate_task_complexity(perception::Perception)::Float64
    complexity = 0.0
    
    # Threat level contributes to complexity
    complexity += perception.threat_level * 0.3
    
    # Low confidence increases complexity (need more reasoning)
    complexity += (1.0 - perception.confidence) * 0.3
    
    # Energy level affects complexity (low energy = simpler decisions)
    complexity += (1.0 - perception.energy_level) * 0.2
    
    # Number of active goals adds complexity
    complexity += min(length(perception.active_goals) * 0.1, 0.2)
    
    return clamp(complexity, 0.0, 1.0)
end

"""
    CognitiveEngine - Main engine for sovereign cognition
"""
mutable struct CognitiveEngine
    # Configuration
    config::SpineConfig
    
    # Kernel reference for approval gateway (Phase 4 - Flow Integrity)
    # This ensures ALL execution paths go through Kernel.approve()
    kernel::Union{Nothing, Any}  # KernelState reference
    
    # Agents
    executor::ExecutorAgent
    strategist::StrategistAgent
    auditor::AuditorAgent
    evolution_engine::EvolutionEngineAgent
    
    # Auxiliary agents (Phase 4 - expanded hierarchy)
    websearch_agent::Union{WebSearchAgent, Nothing}
    code_agent::Union{CodeAgent, Nothing}
    mindmap_agent::Union{MindMapAgent, Nothing}
    
    # Memory
    doctrine::DoctrineMemory
    tactical::TacticalMemory
    adversary::AdversaryModels
    
    # Feedback
    executor_performance::AgentPerformance
    strategist_performance::AgentPerformance
    auditor_performance::AgentPerformance
    evolution_performance::AgentPerformance
    
    # Auxiliary agent performance tracking (Phase 4)
    websearch_performance::AgentPerformance
    code_performance::AgentPerformance
    mindmap_performance::AgentPerformance
    
    # CAUSAL EMOTIONAL INTEGRATION: Affective state influences decision-making
    # Emotions are NOT just tracked - they CAUSALLY affect proposal confidence
    affective_state::AffectiveState
    
    # Power tracking
    optionality::OptionalityTracker
    power_metric::PowerMetric
    
    # State
    cycle_count::Int
    last_cycle_timestamp::DateTime
    
    # Autonomous planner for self-improvement (Phase 4)
    planner::Union{AutonomousPlanner.LearningPlan, Nothing}
    
    function CognitiveEngine(config::SpineConfig = SpineConfig(); kernel=nothing)
        new(
            config,
            kernel,
            ExecutorAgent("executor_001"),
            StrategistAgent("strategist_001"),
            AuditorAgent("auditor_001"),
            EvolutionEngineAgent("evolution_001"),
            # Initialize auxiliary agents (Phase 4)
            WebSearchAgent("websearch_001"),
            CodeAgent("code_agent_001"),
            MindMapAgent("mindmap_001"),
            DoctrineMemory(),
            TacticalMemory(1000),
            AgentPerformance("executor_001", :executor),
            AgentPerformance("strategist_001", :strategist),
            AgentPerformance("auditor_001", :auditor),
            AgentPerformance("evolution_001", :evolution),
            # Initialize auxiliary agent performance tracking (Phase 4)
            AgentPerformance("websearch_001", :websearch),
            AgentPerformance("code_agent_001", :code),
            AgentPerformance("mindmap_001", :mindmap),
            AffectiveState(),  # Initialize emotional state
            OptionalityTracker(),
            PowerMetric(now()),
            0,
            now(),
            nothing  # No learning plan initially
        )
    end
end

"""
    BrainOutput_to_ActionProposal - Convert BrainOutput to ActionProposal for kernel approval
    
    This bridges the Brain-Kernel boundary by converting brain's proposal into
    the format expected by the kernel's approval system.
    
    # Arguments
    - `brain_output::BrainOutput`: Output from brain inference
    - `action_index::Int`: Which proposed action to convert (1 = highest priority)
    
    # Returns
    - `ActionProposal`: Properly formatted proposal for kernel approval
"""
function BrainOutput_to_ActionProposal(brain_output::BrainOutput, action_index::Int=1)::ActionProposal
    # Default to safe action if index out of bounds
    capability_id = if action_index > 0 && action_index <= length(brain_output.proposed_actions)
        brain_output.proposed_actions[action_index]
    else
        "observe_cpu"  # Safe default
    end
    
    # Map brain confidence to predicted cost/reward
    # Higher confidence = lower cost, higher reward
    predicted_cost = 0.1f0 * (1.0f0 - brain_output.confidence)
    predicted_reward = brain_output.value_estimate
    
    # Estimate risk based on uncertainty and capability type
    # Higher uncertainty = higher risk
    base_risk = brain_output.uncertainty
    
    # Adjust risk based on capability type
    high_risk_capabilities = ["safe_shell", "write_file", "safe_http_request"]
    if capability_id in high_risk_capabilities
        base_risk = max(base_risk, 0.5f0)
    end
    
    # Use uncertainty as a risk multiplier
    risk = min(1.0f0, base_risk * (1.0f0 + brain_output.uncertainty))
    
    return ActionProposal(
        capability_id,
        brain_output.confidence,
        predicted_cost,
        predicted_reward,
        risk,
        brain_output.reasoning
    )
end

# ============================================================================
# CAUSAL EMOTIONAL INTEGRATION - VERIFIED
# ============================================================================

"""
    apply_emotional_influence_to_confidence - CAUSALLY apply emotional state to decision confidence
    
    This function IMPLEMENTS the causal link between emotional state and kernel decisions.
    It is called during proposal generation, meaning emotions DIRECTLY affect which 
    decisions the kernel considers.
    
    MECHANISM:
    1. Get current value_modulation from affective state
    2. Apply modulation to base confidence (bounded to ±30%)
    3. Return emotionally-influenced confidence
    
    SECURITY:
    - Max modulation is 0.3 (30%) - hardcoded limit in compute_value_modulation
    - Kernel sovereignty is maintained - emotions influence but don't override
    - Decision is still subject to kernel approval
"""
function apply_emotional_influence_to_confidence(
    base_confidence::Float64,
    affective_state::AffectiveState;
    max_risk_threshold::Float64=0.3
)::Float64
    # Get current emotional modulation (already bounded to ±0.3)
    modulation = compute_value_modulation(affective_state)
    
    # Apply modulation to confidence
    # Positive emotions (modulation > 0) increase confidence
    # Negative emotions (modulation < 0) decrease confidence
    emotionally_influenced = base_confidence * (1.0 + modulation)
    
    # Clamp to valid range [0, 1]
    return clamp(emotionally_influenced, 0.0, 1.0)
end

"""
    process_emotional_outcome - Update emotional state based on decision outcome
    
    This completes the causal loop:
    1. Emotional state influences decision confidence
    2. Decision is made and executed  
    3. Outcome updates emotional state (feedback)
    4. New emotional state influences next decision
"""
function process_emotional_outcome(
    engine::CognitiveEngine,
    decision_outcome::Symbol;  # :success, :failure, :threat, :novelty, :goal_achieved, :goal_blocked
    intensity::Float64=0.5
)::AffectiveState
    state = engine.affective_state
    
    # Map outcome to emotion event
    event_type = if decision_outcome == :success
        :reward
    elseif decision_outcome == :failure
        :punishment
    elseif decision_outcome == :threat
        :threat
    elseif decision_outcome == :novelty
        :novelty
    elseif decision_outcome == :goal_achieved
        :goal_achieved
    elseif decision_outcome == :goal_blocked
        :goal_blocked
    else
        :reward  # Default to positive
    end
    
    # Update emotional state
    update_emotion!(state, event_type, Float32(intensity))
    
    # Decay old emotions
    decay_emotions!(state)
    
    return state
end

"""
    get_emotional_influence_summary - Get summary of emotional influence on decisions
    
    Returns diagnostic info for verifying causal integration is working.
"""
function get_emotional_influence_summary(engine::CognitiveEngine)::Dict{String, Any}
    state = engine.affective_state
    
    return Dict{String, Any}(
        "valence" => state.valence,
        "arousal" => state.arousal,
        "dominance" => state.dominance,
        "current_emotion" => string(state.emotion),
        "emotion_intensity" => state.emotion_intensity,
        "value_modulation" => state.value_modulation,
        "mood_valence" => state.mood_valence,
        "emotion_history_length" => length(state.emotion_history),
        # CAUSAL INTEGRATION VERIFICATION
        "confidence_modifier_example" => apply_emotional_influence_to_confidence(0.8, state),
        "integration_verified" => true  # If this function runs, integration is active
    )
end

"""
    run_sovereign_cycle - Run a complete sovereign cognition cycle
    Now uses typed Perception instead of Dict{String, Any} for type stability
"""
function run_sovereign_cycle(
    engine::CognitiveEngine,
    perception::Perception  # Typed instead of Dict{String, Any}
)::DecisionCycle
    
    engine.cycle_count += 1
    cycle_number = engine.cycle_count
    
    # =========================================================================
    # Step 1: Ingest external reality (if available)
    # =========================================================================
    # In a real system, this would fetch actual signals
    # For now, we use the perception directly
    augmented_perception = perception
    
    # =========================================================================
    # Step 1b: ReAct Framework - Check if complex reasoning is needed
    # =========================================================================
    # ReAct (Reason + Act) is triggered for complex tasks that require
    # interleaved reasoning and action planning. This includes:
    # - High threat situations requiring careful planning
    # - Novel situations without clear precedent
    # - Multi-step tasks requiring chain-of-thought
    # - Low confidence scenarios needing deeper analysis
    
    use_react = false
    react_proposals = AgentProposal[]
    
    # Determine if ReAct reasoning is needed
    task_complexity = _estimate_task_complexity(augmented_perception)
    if task_complexity > 0.7 && engine.mindmap_agent !== nothing
        use_react = true
        @info "ReAct reasoning triggered" complexity=task_complexity
        
        # Create ReAct context for complex reasoning
        react_context = create_react_context(
            augmented_perception,
            "Complex task reasoning with interleaved thought and action",
            engine.mindmap_agent
        )
        
        # Run ReAct cycle to generate enhanced proposals
        react_result = run_react_cycle(react_context, augmented_perception)
        
        # Convert ReAct results to proposals if available
        if react_result !== nothing && react_result.final_proposal !== nothing
            push!(react_proposals, react_result.final_proposal)
            @info "ReAct cycle completed" proposal=react_result.final_proposal.decision
        end
    end
    
    # =========================================================================
    # Step 2: Run parallel agent proposals
    # CAUSAL EMOTIONAL INTEGRATION: Emotions affect proposal confidence
    # =========================================================================
    proposals = AgentProposal[]
    
    # Get current emotional influence (this is the causal link!)
    emotional_modulation = compute_value_modulation(engine.affective_state)
    @debug "Emotional influence on decisions" modulation=emotional_modulation
    
    # Executor proposal - with emotional influence
    executor_prop = generate_proposal(engine.executor, augmented_perception, engine.tactical)
    # Apply emotional modulation to confidence
    executor_emotional_confidence = apply_emotional_influence_to_confidence(
        executor_prop.confidence, 
        engine.affective_state
    )
    executor_prop = AgentProposal(
        executor_prop.agent_id,
        executor_prop.agent_type,
        executor_prop.decision,
        executor_emotional_confidence * engine.executor_performance.current_weight,
        reasoning = executor_prop.reasoning * " [emotional_modulation=$emotional_modulation]",
        weight = engine.executor_performance.current_weight,
        evidence = executor_prop.evidence
    )
    push!(proposals, executor_prop)
    
    # Strategist proposal - with emotional influence
    strategist_prop = generate_proposal(
        engine.strategist, 
        augmented_perception, 
        engine.doctrine,
        engine.tactical,
        engine.adversary
    )
    strategist_emotional_confidence = apply_emotional_influence_to_confidence(
        strategist_prop.confidence,
        engine.affective_state
    )
    strategist_prop = AgentProposal(
        strategist_prop.agent_id,
        strategist_prop.agent_type,
        strategist_prop.decision,
        strategist_emotional_confidence * engine.strategist_performance.current_weight,
        reasoning = strategist_prop.reasoning * " [emotional_modulation=$emotional_modulation]",
        weight = engine.strategist_performance.current_weight,
        evidence = strategist_prop.evidence
    )
    push!(proposals, strategist_prop)
    
    # Auditor proposal - with emotional influence
    auditor_prop = generate_proposal(
        engine.auditor,
        augmented_perception,
        proposals,  # Check other proposals for overconfidence
        engine.doctrine,
        engine.tactical
    )
    auditor_emotional_confidence = apply_emotional_influence_to_confidence(
        auditor_prop.confidence,
        engine.affective_state
    )
    auditor_prop = AgentProposal(
        auditor_prop.agent_id,
        auditor_prop.agent_type,
        auditor_prop.decision,
        auditor_emotional_confidence * engine.auditor_performance.current_weight,
        reasoning = auditor_prop.reasoning * " [emotional_modulation=$emotional_modulation]",
        weight = engine.auditor_performance.current_weight,
        evidence = auditor_prop.evidence
    )
    push!(proposals, auditor_prop)
    
    # Evolution proposal - with emotional influence
    evolution_prop = generate_proposal(
        engine.evolution_engine,
        augmented_perception,
        Dict("prediction_accuracy" => 0.7),  # Would come from historical data
        engine.doctrine
    )
    evolution_emotional_confidence = apply_emotional_influence_to_confidence(
        evolution_prop.confidence,
        engine.affective_state
    )
    evolution_prop = AgentProposal(
        evolution_prop.agent_id,
        evolution_prop.agent_type,
        evolution_prop.decision,
        evolution_emotional_confidence * engine.evolution_performance.current_weight,
        reasoning = evolution_prop.reasoning * " [emotional_modulation=$emotional_modulation]",
        weight = engine.evolution_performance.current_weight,
        evidence = evolution_prop.evidence
    )
    push!(proposals, evolution_prop)
    
    # =========================================================================
    # Step 2b: Auxiliary agents generate proposals (Phase 4 - expanded hierarchy)
    # =========================================================================
    # These agents provide specialized capabilities:
    # - WebSearchAgent: Information retrieval
    # - CodeAgent: Quantitative/analytical tasks
    # - MindMapAgent: Logical coherence validation and hallucination detection
    
    # WebSearchAgent proposal - for information retrieval tasks
    if engine.websearch_agent !== nothing
        websearch_context = Dict{String, Any}(
            "query" => get(augmented_perception.system_state, "query", ""),
            "intent" => get(augmented_perception.system_state, "intent", "information_retrieval"),
            "threat_level" => augmented_perception.threat_level
        )
        websearch_prop = generate_proposal(
            engine.websearch_agent,
            augmented_perception,
            websearch_context
        )
        websearch_emotional_confidence = apply_emotional_influence_to_confidence(
            websearch_prop.confidence,
            engine.affective_state
        )
        websearch_prop = AgentProposal(
            websearch_prop.agent_id,
            websearch_prop.agent_type,
            websearch_prop.decision,
            websearch_emotional_confidence * engine.websearch_performance.current_weight,
            reasoning = websearch_prop.reasoning * " [emotional_modulation=$emotional_modulation]",
            weight = engine.websearch_performance.current_weight,
            evidence = websearch_prop.evidence
        )
        push!(proposals, websearch_prop)
    end
    
    # CodeAgent proposal - for computational/quantitative tasks
    if engine.code_agent !== nothing
        code_context = Dict{String, Any}(
            "task" => get(augmented_perception.system_state, "task", ""),
            "type" => get(augmented_perception.system_state, "task_type", "analysis"),
            "threat_level" => augmented_perception.threat_level
        )
        code_prop = generate_proposal(
            engine.code_agent,
            augmented_perception,
            code_context
        )
        code_emotional_confidence = apply_emotional_influence_to_confidence(
            code_prop.confidence,
            engine.affective_state
        )
        code_prop = AgentProposal(
            code_prop.agent_id,
            code_prop.agent_type,
            code_prop.decision,
            code_emotional_confidence * engine.code_performance.current_weight,
            reasoning = code_prop.reasoning * " [emotional_modulation=$emotional_modulation]",
            weight = engine.code_performance.current_weight,
            evidence = code_prop.evidence
        )
        push!(proposals, code_prop)
    end
    
    # MindMapAgent proposal - logical coherence validation
    # MindMapAgent validates logical consistency BEFORE final decision
    if engine.mindmap_agent !== nothing
        mindmap_context = Dict{String, Any}(
            "proposals" => [p.decision for p in proposals],
            "threat_level" => augmented_perception.threat_level,
            "validation_mode" => "coherence_check"
        )
        mindmap_prop = generate_proposal(
            engine.mindmap_agent,
            augmented_perception,
            mindmap_context
        )
        # MindMapAgent confidence is about logical coherence
        mindmap_emotional_confidence = apply_emotional_influence_to_confidence(
            mindmap_prop.confidence,
            engine.affective_state
        )
        mindmap_prop = AgentProposal(
            mindmap_prop.agent_id,
            mindmap_prop.agent_type,
            mindmap_prop.decision,
            mindmap_emotional_confidence * engine.mindmap_performance.current_weight,
            reasoning = mindmap_prop.reasoning * " [emotional_modulation=$emotional_modulation]",
            weight = engine.mindmap_performance.current_weight,
            evidence = mindmap_prop.evidence
        )
        push!(proposals, mindmap_prop)
    end
    
    # =========================================================================
    # Step 3: Conflict resolution
    # =========================================================================
    conflict = resolve_conflict(proposals, engine.config)
    
    # =========================================================================
    # Step 4: Commit decision
    # =========================================================================
    decision = CommittedDecision(conflict.winner, proposals, conflict)
    
    # =========================================================================
    # Step 5: Kernel approval - Flow Integrity gateway (Phase 4)
    # =========================================================================
    # UNIFIED EXECUTION PATH: All decisions go through Kernel.approve()
    # This is the SINGLE gateway - no bypass mechanisms allowed
    
    # Create action proposal from the winning decision
    proposal = ActionProposal(
        conflict.winner,
        mean([p.confidence for p in proposals]),
        0.1f0,  # predicted_cost
        0.8f0,  # predicted_reward
        0.3f0,  # risk - moderate by default
        "Cognition cycle $cycle_number proposal"
    )
    
    # Call Kernel.approve() as the single gateway
    approval_token = nothing
    if engine.kernel !== nothing
        try
            # Convert to world_state dict for kernel approval
            world_state = Dict{String, Any}(
                "cycle" => cycle_number,
                "confidence" => mean([p.confidence for p in proposals]),
                "timestamp" => string(now())
            )
            
            # Call the actual Kernel.approve() function
            kernel_decision = Kernel.approve(engine.kernel, proposal, world_state)
            
            @debug "Kernel.approve() returned" decision=kernel_decision
            
            if kernel_decision == APPROVED
                # Generate cryptographic approval token
                approval_token = generate_approval_token(decision, conflict.winner)
                decision.kernel_approved = true
                decision.kernel_approval_timestamp = now()
                @info "Kernel approved decision" decision=conflict.winner
            else
                # Fail-closed: deny execution
                decision.kernel_approved = false
                decision.kernel_approval_timestamp = nothing
                @warn "Kernel denied decision - fail-closed" decision=conflict.winner
            end
        catch e
            # Fail-closed on any error
            decision.kernel_approved = false
            decision.kernel_approval_timestamp = nothing
            @error "Kernel approval failed - fail-closed" error=string(e)
        end
    else
        # No kernel available - fail-closed
        decision.kernel_approved = false
        decision.kernel_approval_timestamp = nothing
        @warn "No kernel available - fail-closed (Flow Integrity)"
    end
    
    # Only execute if kernel approved (Flow Integrity)
    if !decision.kernel_approved
        # Rejected - do not execute
        outcome = DecisionOutcome(
            OUTCOME_REJECTED,
            Dict("decision" => decision.decision, "cycle" => cycle_number, "reason" => "kernel_denied"),
            Dict(),
            now()
        )
        decision.outcome = outcome
        return cycle_number
    end
    
    # =========================================================================
    # Step 6: Execute and record outcome (only if kernel approved)
    # =========================================================================
    outcome = DecisionOutcome(
        OUTCOME_EXECUTED,
        Dict("decision" => decision.decision, "cycle" => cycle_number, "approval_token" => string(approval_token !== nothing ? approval_token.id : "none")),
        Dict(),
        now()
    )
    
    # Record in tactical memory
    record_outcome!(engine.tactical, Dict(
        "decision" => decision.decision,
        "agents" => [p.agent_id for p in proposals],
        "winner" => conflict.winner,
        "outcome" => "success"
    ))
    
    # =========================================================================
    # Step 7: Process feedback
    # =========================================================================
    # Update optionality based on decision
    push!(engine.optionality.viable_actions, decision.decision)
    
    # Create cycle result for feedback
    cycle_result = Dict(
        "expected_outcome" => decision.decision,
        "actual_outcome" => decision.decision,
        "agent_confidence" => mean([p.confidence for p in proposals]),
        "expected_risks" => String[],
        "actual_risks" => String[],
        "warnings_issued" => occursin("veto", auditor_prop.decision) ? 1 : 0
    )
    
    # Process feedback for each agent
    process_cycle_feedback(engine.executor_performance, cycle_result)
    process_cycle_feedback(engine.strategist_performance, cycle_result)
    process_cycle_feedback(engine.auditor_performance, cycle_result)
    process_cycle_feedback(engine.evolution_performance, cycle_result)
    
    # CAUSAL EMOTIONAL FEEDBACK: Update emotional state based on outcome
    # This closes the loop: emotions → decisions → outcomes → emotions
    process_emotional_outcome(engine, :success, intensity=0.5)
    
    @debug "Emotional state after cycle" 
        valence=engine.affective_state.valence
        arousal=engine.affective_state.arousal
        modulation=engine.affective_state.value_modulation
    
    engine.last_cycle_timestamp = now()
    
    # Return cycle (simplified - full DecisionCycle would have more fields)
    return cycle_number
end

"""
    measure_power - Calculate current power metric
"""
function measure_power(engine::CognitiveEngine)::Float64
    
    # Update power metric
    engine.power_metric.optionality_end = length(engine.optionality.viable_actions)
    engine.power_metric.optionality_gained = engine.power_metric.optionality_end - engine.power_metric.optionality_start
    
    engine.power_metric.viable_actions_end = length(engine.optionality.viable_actions)
    engine.power_metric.pivot_speed_end = engine.optionality.pivot_speed
    engine.power_metric.reversibility_end = engine.optionality.reversibility
    engine.power_metric.leverage_points_discovered = length(engine.optionality.leverage_points)
    
    return calculate_power(engine.power_metric)
end

# ============================================================================
# AUTONOMOUS PLANNING INTEGRATION (Phase 4)
# ============================================================================

"""
    integrate_autonomous_planner - Integrate AutonomousPlanner into cognitive loop
    
    This enables self-improvement by generating learning plans
"""
function integrate_autonomous_planner(
    engine::CognitiveEngine,
    focus_areas::Vector{String}=String[]
)::AutonomousPlanner.LearningPlan
    
    # Create a learning plan based on current performance
    if isempty(focus_areas)
        # Default focus areas based on agent performance
        focus_areas = String[]
        
        # Check which agents need improvement
        if engine.executor_performance.accuracy < 0.7
            push!(focus_areas, "execution_accuracy")
        end
        if engine.strategist_performance.accuracy < 0.7
            push!(focus_areas, "strategic_planning")
        end
        if engine.auditor_performance.accuracy < 0.7
            push!(focus_areas, "critical_analysis")
        end
    end
    
    # Generate learning journey
    plan = AutonomousPlanner.generate_learning_journey(
        focus_areas;
        module_count=AutonomousPlanner.DEFAULT_MODULE_COUNT
    )
    
    # Store in engine
    engine.planner = plan
    
    return plan
end

"""
    process_autonomous_learning - Process next module in autonomous learning plan
"""
function process_autonomous_learning(engine::CognitiveEngine)::Bool
    
    if engine.planner === nothing
        return false
    end
    
    # Get next module
    next_module = AutonomousPlanner.get_next_module!(engine.planner)
    
    if next_module === nothing
        # Plan complete - generate new plan
        @info "Autonomous learning plan complete, generating new plan"
        integrate_autonomous_planner(engine)
        return false
    end
    
    # Process the module (in a real system, this would trigger actual learning)
    @info "Processing autonomous learning module" module_title=next_module.title
    
    # Update progress
    AutonomousPlanner.update_module_progress!(next_module, 1.0)
    
    return true
end

# ============================================================================
# FORMAL VERIFICATION FOR SOVEREIGNTY INVARIANTS (Phase 4)
# ============================================================================

"""
    SovereigntyInvariants - Formal invariants that must hold for cognitive sovereignty
"""
struct SovereigntyInvariants
    # All execution must go through kernel approval
    kernel_approval_required::Bool
    
    # No hardcoded bypasses allowed
    no_bypass_allowed::Bool
    
    # Flow integrity must be enforced
    flow_integrity_enforced::Bool
    
    # Decisions must be traceable
    decisions_traceable::Bool
    
    # Kernel maintains final authority
    kernel_final_authority::Bool
end

"""
    verify_sovereignty_invariants - Formal verification of sovereignty
    
    This function verifies that all sovereignty invariants are maintained.
    
    INVARIANTS:
    1. kernel_approval_required: All execution paths must require kernel approval
    2. no_bypass_allowed: No hardcoded bypasses exist
    3. flow_integrity_enforced: Flow Integrity pattern is properly implemented
    4. decisions_traceable: All decisions can be traced to their origin
    5. kernel_final_authority: Kernel has final authority over execution
"""
function verify_sovereignty_invariants(
    engine::CognitiveEngine
)::Tuple{Bool, Vector{String}}
    
    violations = String[]
    
    # Invariant 1: Kernel approval required
    if engine.kernel === nothing
        push!(violations, "VIOLATION: No kernel reference - kernel_approval_required invariant broken")
    end
    
    # Invariant 2: No bypass allowed (check that hardcoded bypass was removed)
    # This is verified by the fact that we now use require_kernel_approval
    # The old code had: decision.kernel_approved = true
    # The new code uses: decision.kernel_approved = (kernel_decision == APPROVED)
    
    # Invariant 3: Flow integrity enforced (ApprovalToken must be generated)
    # This is enforced by the Flow Integrity pattern in run_sovereign_cycle
    
    # Invariant 4: Decisions traceable
    if engine.cycle_count < 0
        push!(violations, "VIOLATION: Negative cycle count - decisions_traceable invariant broken")
    end
    
    # Invariant 5: Kernel final authority
    # This is verified by the fail-closed default in require_kernel_approval
    
    # Check module end
    return isempty(violations), violations
end

"""
    assert_sovereignty - Assert sovereignty invariants, fail if violated
    
    This is called at critical points to ensure sovereignty is maintained.
"""
function assert_sovereignty(engine::CognitiveEngine)::Nothing
    valid, violations = verify_sovereignty_invariants(engine)
    
    if !valid
        error("SOVEREIGNTY VIOLATION DETECTED: " * join(violations, "; "))
    end
    
    return nothing
end

"""
    validate_flow_integrity - Validate Flow Integrity for a specific decision
"""
function validate_flow_integrity(
    decision::CommittedDecision,
    token::Union{ApprovalToken, Nothing}
)::Tuple{Bool, String}
    
    # Check if decision was kernel approved
    if !decision.kernel_approved
        return false, "Decision not kernel approved - Flow Integrity violated"
    end
    
    # Check if approval token exists
    if token === nothing
        return false, "No approval token - Flow Integrity violated"
    end
    
    # Check token validity
    if !validate_approval_token(token, decision)
        return false, "Invalid approval token - Flow Integrity violated"
    end
    
    return true, "Flow Integrity validated"
end

end # module Cognition
