//! ITHERIS gRPC Client Service
//! 
//! Provides gRPC client connection to the Warden service for streaming
//! metabolic updates and fetching decision proposals.

use crate::state::signals::MetabolicSignals;
use anyhow::{Context, Result};
use std::sync::Arc;
use tokio::sync::mpsc;
use tonic::metadata::MetadataMap;
use tonic::transport::Channel;
use tonic::Request;
use tracing::{error, info, warn};

/// Protobuf generated types (will be generated by tonic-build)
pub mod proto {
    include!("../proto/warden.rs");
}

use proto::*;

/// Warden gRPC client wrapper
pub struct WardenClient {
    /// The underlying tonic client
    client: proto::warden_service_client::WardenServiceClient<Channel>,
    /// Metabolic state signals
    metabolic_signals: MetabolicSignals,
}

impl WardenClient {
    /// Create a new WardenClient connection
    pub async fn connect(addr: &str) -> Result<Self> {
        let channel = Channel::from_shared(addr.to_string())
            .context("Invalid address")?
            .connect()
            .await
            .context("Failed to connect to Warden service")?;

        let client = proto::warden_service_client::WardenServiceClient::new(channel);

        Ok(Self {
            client,
            metabolic_signals: MetabolicSignals::new(),
        })
    }

    /// Subscribe to metabolic telemetry stream
    pub async fn subscribe_metabolic(&mut self) -> Result<()>
    where
        Self: Sized,
    {
        info!("Subscribing to metabolic telemetry stream");

        let request = Request::new(Empty {});

        let mut stream = self
            .client
            .subscribe_metabolic(request)
            .await
            .context("Failed to subscribe to metabolic stream")?
            .into_inner();

        info!("Metabolic stream connected, processing updates...");

        while let Some(snapshot) = stream.message().await? {
            self.handle_metabolic_snapshot(snapshot);
        }

        warn!("Metabolic stream closed by server");
        Ok(())
    }

    /// Handle incoming metabolic snapshot
    fn handle_metabolic_snapshot(&self, snapshot: MetabolicSnapshot) {
        let energy = snapshot.energy_level;
        let viability = snapshot.viability_budget;
        let tick_count = snapshot.tick_count;
        let cognitive_mode = snapshot.cognitive_mode;
        let is_dreaming = snapshot.is_dreaming;

        info!(
            energy = energy,
            viability = viability,
            tick_count = tick_count,
            mode = cognitive_mode,
            "Metabolic snapshot received"
        );

        self.metabolic_signals.update_from_snapshot(
            energy,
            viability,
            tick_count,
            &cognitive_mode,
            is_dreaming,
        );
    }

    /// Fetch decision proposals stream
    pub async fn get_proposals(&mut self) -> Result<Vec<Proposal>> 
    where
        Self: Sized,
    {
        info!("Fetching decision proposals");

        let request = Request::new(Empty {});

        let mut stream = self
            .client
            .get_proposals(request)
            .await
            .context("Failed to get proposals stream")?
            .into_inner();

        let mut proposals = Vec::new();

        while let Some(proposal) = stream.message().await? {
            proposals.push(proposal);
        }

        info!(count = proposals.len(), "Received proposals");
        Ok(proposals)
    }

    /// Request TPM unsealing
    pub async fn request_unsealing(
        &mut self,
        pcr_values: Vec<Vec<u8>>,
        auth: String,
    ) -> Result<UnsealingResponse>
    where
        Self: Sized,
    {
        info!("Requesting TPM unsealing");

        let request = Request::new(UnsealingRequest {
            pcr_values,
            auth,
        });

        let response = self
            .client
            .request_unsealing(request)
            .await
            .context("Failed to request unsealing")?
            .into_inner();

        if response.success {
            info!("TPM unsealing successful");
        } else {
            error!("TPM unsealing failed: {}", response.error);
        }

        Ok(response)
    }

    /// Get the metabolic signals
    pub fn metabolic_signals(&self) -> &MetabolicSignals {
        &self.metabolic_signals
    }
}

/// Build metadata for gRPC requests
pub fn build_metadata(auth_token: Option<&str>) -> Result<MetadataMap> {
    let mut metadata = MetadataMap::new();

    if let Some(token) = auth_token {
        metadata.insert(
            "authorization",
            token.parse().context("Invalid auth token")?,
        );
    }

    Ok(metadata)
}

/// Create a background task for metabolic streaming
pub async fn start_metabolic_stream(
    addr: String,
    metabolic_signals: MetabolicSignals,
) -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
    info!(addr = addr, "Starting metabolic stream background task");

    loop {
        let mut client = match WardenClient::connect(&addr).await {
            Ok(c) => c,
            Err(e) => {
                error!(error = %e, "Failed to connect to Warden, retrying in 5s");
                tokio::time::sleep(tokio::time::Duration::from_secs(5)).await;
                continue;
            }
        };

        if let Err(e) = client.subscribe_metabolic().await {
            error!(error = %e, "Metabolic stream error, reconnecting");
            tokio::time::sleep(tokio::time::Duration::from_secs(1)).await;
        }
    }
}

/// Connection configuration for Warden client
#[derive(Debug, Clone)]
pub struct WardenConfig {
    /// gRPC address (e.g., "http://localhost:50051")
    pub address: String,
    /// Connection timeout in seconds
    pub timeout_secs: u64,
    /// Enable TLS
    pub use_tls: bool,
}

impl Default for WardenConfig {
    fn default() -> Self {
        Self {
            address: "http://localhost:50051".to_string(),
            timeout_secs: 30,
            use_tls: false,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_warden_config_default() {
        let config = WardenConfig::default();
        assert_eq!(config.address, "http://localhost:50051");
        assert_eq!(config.timeout_secs, 30);
        assert!(!config.use_tls);
    }

    #[test]
    fn test_metadata_builder() {
        let metadata = build_metadata(Some("Bearer token123")).unwrap();
        assert!(metadata.contains_key("authorization"));
    }
}
