//! ITHERIS Generated Protocol Buffer Types
//! 
//! This file is auto-generated by tonic-build from warden.proto.
//! DO NOT EDIT - this file will be regenerated during build.

use prost::Message;

/// MetabolicSnapshot represents the current metabolic state of the system.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MetabolicSnapshot {
    /// Current energy level (0.0 - 1.0)
    #[prost(double, tag = "1")]
    pub energy_level: f64,
    /// Viability budget remaining (0.0 - 1.0)
    #[prost(double, tag = "2")]
    pub viability_budget: f64,
    /// Total tick count since system initialization
    #[prost(uint64, tag = "3")]
    pub tick_count: u64,
    /// Current cognitive mode
    #[prost(string, tag = "4")]
    pub cognitive_mode: ::prost::alloc::string::String,
    /// Whether the system is in dreaming/oneiric state
    #[prost(bool, tag = "5")]
    pub is_dreaming: bool,
}

/// Proposal represents a decision proposal from the Decision Spine
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Proposal {
    /// Unique identifier for this proposal
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// Human-readable rationale for this proposal
    #[prost(string, tag = "2")]
    pub rationale: ::prost::alloc::string::String,
    /// Priority level (0.0 - 1.0)
    #[prost(double, tag = "3")]
    pub priority: f64,
    /// Expected reward from executing this proposal
    #[prost(double, tag = "4")]
    pub reward: f64,
    /// Risk level associated with this proposal
    #[prost(double, tag = "5")]
    pub risk: f64,
    /// Calculated score (reward - risk)
    #[prost(double, tag = "6")]
    pub score: f64,
    /// Whether this proposal has been approved
    #[prost(bool, tag = "7")]
    pub approved: bool,
    /// Hallucination detection score
    #[prost(double, tag = "8")]
    pub hallucination_score: f64,
    /// Reason for veto if rejected
    #[prost(string, tag = "9")]
    pub veto_reason: ::prost::alloc::string::String,
}

/// Empty message for streaming subscriptions
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Empty {
}

/// UnsealingRequest represents a request to unseal TPM-protected data
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UnsealingRequest {
    /// PCR values to verify
    #[prost(bytes = "vec", tag = "1")]
    pub pcr_values: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    /// Authentication string
    #[prost(string, tag = "2")]
    pub auth: ::prost::alloc::string::String,
}

/// UnsealingResponse represents the result of an unsealing operation
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UnsealingResponse {
    /// Whether the unsealing was successful
    #[prost(bool, tag = "1")]
    pub success: bool,
    /// Unsealed data (if successful)
    #[prost(bytes, tag = "2")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    /// Error message if failed
    #[prost(string, tag = "3")]
    pub error: ::prost::alloc::string::String,
}

/// Generated client implementations.
pub mod warden_service_client {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::channel::Channel;
    use tonic::codegen::*;
    use tonic::transport::Channel;
    
    /// WardenService provides the core management interface for ITHERIS
    #[derive(Debug, Clone)]
    pub struct WardenServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    
    impl<T> WardenServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        
        pub fn with_channel(inner: T) -> Self {
            Self::new(inner)
        }
        
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: std::convert::TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
        
        /// Subscribe to metabolic telemetry updates
        pub async fn subscribe_metabolic(
            &mut self,
            request: impl tonic::IntoRequest<super::Empty>,
        ) -> Result<tonic::Response<tonic::codec::Streaming<super::MetabolicSnapshot>>, tonic::Status> {
            self.inner.ready().await.map_err(|e| tonic::Status::new( tonic::Code::Unknown, e.to_string()))?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/warden.WardenService/SubscribeMetabolic");
            self.inner.server_streaming(request.into_request(), path, codec).await
        }
        
        /// Stream decision proposals from the Decision Spine
        pub async fn get_proposals(
            &mut self,
            request: impl tonic::IntoRequest<super::Empty>,
        ) -> Result<tonic::Response<tonic::codec::Streaming<super::Proposal>>, tonic::Status> {
            self.inner.ready().await.map_err(|e| tonic::Status::new( tonic::Code::Unknown, e.to_string()))?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/warden.WardenService/GetProposals");
            self.inner.server_streaming(request.into_request(), path, codec).await
        }
        
        /// Request TPM unsealing for secure operations
        pub async fn request_unsealing(
            &mut self,
            request: impl tonic::IntoRequest<super::UnsealingRequest>,
        ) -> Result<tonic::Response<super::UnsealingResponse>, tonic::Status> {
            self.inner.ready().await.map_err(|e| tonic::Status::new( tonic::Code::Unknown, e.to_string()))?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/warden.WardenService/RequestUnsealing");
            self.inner.unary(request.into_request(), path, codec).await
        }
    }
}
